//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 02:03:21 PM CEST 
//


package korenski.soap.odobrenjertgs;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OdobrenjeRtgs complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OdobrenjeRtgs">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="RtgsElement" type="{http://korenski/soap/odobrenjertgs}RTGS"/>
 *         &lt;element name="PorukaElement" type="{http://korenski/soap/odobrenjertgs}Poruka"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OdobrenjeRtgs", propOrder = {
    "rtgsElement",
    "porukaElement"
})
@Entity
public class OdobrenjeRtgs {
	
	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	@XmlTransient
	private Long id;
    
	@XmlElement(name = "RtgsElement", required = true)
	@OneToOne(cascade = CascadeType.ALL)
    protected RTGS rtgsElement;
    @XmlElement(name = "PorukaElement", required = true)
    @OneToOne(cascade = CascadeType.ALL)
    protected Poruka porukaElement;
    
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
    
    /**
     * Gets the value of the rtgsElement property.
     * 
     * @return
     *     possible object is
     *     {@link RTGS }
     *     
     */
    public RTGS getRtgsElement() {
        return rtgsElement;
    }

    /**
     * Sets the value of the rtgsElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link RTGS }
     *     
     */
    public void setRtgsElement(RTGS value) {
        this.rtgsElement = value;
    }

    /**
     * Gets the value of the porukaElement property.
     * 
     * @return
     *     possible object is
     *     {@link Poruka }
     *     
     */
    public Poruka getPorukaElement() {
        return porukaElement;
    }

    /**
     * Sets the value of the porukaElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Poruka }
     *     
     */
    public void setPorukaElement(Poruka value) {
        this.porukaElement = value;
    }

}
