//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.20 at 02:03:21 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://korenski/soap/odobrenjertgs", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package korenski.soap.odobrenjertgs;
