//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 01:59:03 PM CEST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://korenski/soap/izvestaji_model", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package korenski.soap.izvestaji_model;
