//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.14 at 02:19:13 PM CEST 
//


package korenski.soap.nalozi_model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * <p>Java class for Nalog_za_prenos complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="Nalog_za_prenos">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ID_poruke">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="50"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Duznik-nalogodavac">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Primalac-poverilac">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Svrha_placanja">
 *           &lt;simpleType>
 *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *               &lt;minLength value="1"/>
 *               &lt;maxLength value="200"/>
 *             &lt;/restriction>
 *           &lt;/simpleType>
 *         &lt;/element>
 *         &lt;element name="Podaci_o_placanju">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="Finansijski_podaci_duznik" type="{http://korenski/soap/nalozi_model}TFinansijski_podaci"/>
 *                   &lt;element name="Finansijski_podaci_poverilac" type="{http://korenski/soap/nalozi_model}TFinansijski_podaci"/>
 *                   &lt;element name="Iznos">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
 *                         &lt;fractionDigits value="2"/>
 *                         &lt;totalDigits value="15"/>
 *                         &lt;minInclusive value="0"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Datum_valute" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                   &lt;element name="Oznaka_valute">
 *                     &lt;simpleType>
 *                       &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *                         &lt;length value="3"/>
 *                         &lt;pattern value="[A-Z]{3}"/>
 *                       &lt;/restriction>
 *                     &lt;/simpleType>
 *                   &lt;/element>
 *                   &lt;element name="Datum_naloga" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *       &lt;attribute name="Hitno" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *             &lt;enumeration value="Da"/>
 *             &lt;enumeration value="Ne"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "Nalog_za_prenos", propOrder = {
    "idPoruke",
    "duznikNalogodavac",
    "primalacPoverilac",
    "svrhaPlacanja",
    "podaciOPlacanju"
})
@Entity
public class NalogZaPrenos {

	@Id
	@GeneratedValue(strategy = GenerationType.IDENTITY)
	@Column(name = "id")
	@XmlTransient
	private Long id;

	@XmlElement(name = "ID_poruke", required = true)
    protected String idPoruke;
    @XmlElement(name = "Duznik-nalogodavac", required = true)
    protected String duznikNalogodavac;
    @XmlElement(name = "Primalac-poverilac", required = true)
    protected String primalacPoverilac;
    @XmlElement(name = "Svrha_placanja", required = true)
    protected String svrhaPlacanja;
    @XmlElement(name = "Podaci_o_placanju", required = true)
    @OneToOne(cascade = CascadeType.ALL)
    protected NalogZaPrenos.PodaciOPlacanju podaciOPlacanju;
    @XmlAttribute(name = "Hitno", required = true)
    protected String hitno;
    
    public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}
    
    /**
     * Gets the value of the idPoruke property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIDPoruke() {
        return idPoruke;
    }

    /**
     * Sets the value of the idPoruke property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIDPoruke(String value) {
        this.idPoruke = value;
    }

    /**
     * Gets the value of the duznikNalogodavac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDuznikNalogodavac() {
        return duznikNalogodavac;
    }

    /**
     * Sets the value of the duznikNalogodavac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDuznikNalogodavac(String value) {
        this.duznikNalogodavac = value;
    }

    /**
     * Gets the value of the primalacPoverilac property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPrimalacPoverilac() {
        return primalacPoverilac;
    }

    /**
     * Sets the value of the primalacPoverilac property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPrimalacPoverilac(String value) {
        this.primalacPoverilac = value;
    }

    /**
     * Gets the value of the svrhaPlacanja property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSvrhaPlacanja() {
        return svrhaPlacanja;
    }

    /**
     * Sets the value of the svrhaPlacanja property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSvrhaPlacanja(String value) {
        this.svrhaPlacanja = value;
    }

    /**
     * Gets the value of the podaciOPlacanju property.
     * 
     * @return
     *     possible object is
     *     {@link NalogZaPrenos.PodaciOPlacanju }
     *     
     */
    public NalogZaPrenos.PodaciOPlacanju getPodaciOPlacanju() {
        return podaciOPlacanju;
    }

    /**
     * Sets the value of the podaciOPlacanju property.
     * 
     * @param value
     *     allowed object is
     *     {@link NalogZaPrenos.PodaciOPlacanju }
     *     
     */
    public void setPodaciOPlacanju(NalogZaPrenos.PodaciOPlacanju value) {
        this.podaciOPlacanju = value;
    }

    /**
     * Gets the value of the hitno property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getHitno() {
        return hitno;
    }

    /**
     * Sets the value of the hitno property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setHitno(String value) {
        this.hitno = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="Finansijski_podaci_duznik" type="{http://korenski/soap/nalozi_model}TFinansijski_podaci"/>
     *         &lt;element name="Finansijski_podaci_poverilac" type="{http://korenski/soap/nalozi_model}TFinansijski_podaci"/>
     *         &lt;element name="Iznos">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}decimal">
     *               &lt;fractionDigits value="2"/>
     *               &lt;totalDigits value="15"/>
     *               &lt;minInclusive value="0"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Datum_valute" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *         &lt;element name="Oznaka_valute">
     *           &lt;simpleType>
     *             &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
     *               &lt;length value="3"/>
     *               &lt;pattern value="[A-Z]{3}"/>
     *             &lt;/restriction>
     *           &lt;/simpleType>
     *         &lt;/element>
     *         &lt;element name="Datum_naloga" type="{http://www.w3.org/2001/XMLSchema}dateTime"/>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {
        "finansijskiPodaciDuznik",
        "finansijskiPodaciPoverilac",
        "iznos",
        "datumValute",
        "oznakaValute",
        "datumNaloga"
    })
    @Entity
    public static class PodaciOPlacanju {
    	
    	@Id
    	@GeneratedValue(strategy = GenerationType.IDENTITY)
    	@Column(name = "id")
    	@XmlTransient
    	private Long id;

		@XmlElement(name = "Finansijski_podaci_duznik", required = true)
		@OneToOne(cascade = CascadeType.ALL)
        protected TFinansijskiPodaci finansijskiPodaciDuznik;
        @XmlElement(name = "Finansijski_podaci_poverilac", required = true)
        @OneToOne(cascade = CascadeType.ALL)
        protected TFinansijskiPodaci finansijskiPodaciPoverilac;
        @XmlElement(name = "Iznos", required = true)
        protected BigDecimal iznos;
        @XmlElement(name = "Datum_valute", required = true)
        @XmlSchemaType(name = "dateTime")
        protected Date datumValute;
        @XmlElement(name = "Oznaka_valute", required = true)
        protected String oznakaValute;
        @XmlElement(name = "Datum_naloga", required = true)
        @XmlSchemaType(name = "dateTime")
        protected Date datumNaloga;
        
        public Long getId() {
			return id;
		}

		public void setId(Long id) {
			this.id = id;
		}
        
        /**
         * Gets the value of the finansijskiPodaciDuznik property.
         * 
         * @return
         *     possible object is
         *     {@link TFinansijskiPodaci }
         *     
         */
        public TFinansijskiPodaci getFinansijskiPodaciDuznik() {
            return finansijskiPodaciDuznik;
        }

        /**
         * Sets the value of the finansijskiPodaciDuznik property.
         * 
         * @param value
         *     allowed object is
         *     {@link TFinansijskiPodaci }
         *     
         */
        public void setFinansijskiPodaciDuznik(TFinansijskiPodaci value) {
            this.finansijskiPodaciDuznik = value;
        }

        /**
         * Gets the value of the finansijskiPodaciPoverilac property.
         * 
         * @return
         *     possible object is
         *     {@link TFinansijskiPodaci }
         *     
         */
        public TFinansijskiPodaci getFinansijskiPodaciPoverilac() {
            return finansijskiPodaciPoverilac;
        }

        /**
         * Sets the value of the finansijskiPodaciPoverilac property.
         * 
         * @param value
         *     allowed object is
         *     {@link TFinansijskiPodaci }
         *     
         */
        public void setFinansijskiPodaciPoverilac(TFinansijskiPodaci value) {
            this.finansijskiPodaciPoverilac = value;
        }

        /**
         * Gets the value of the iznos property.
         * 
         * @return
         *     possible object is
         *     {@link BigDecimal }
         *     
         */
        public BigDecimal getIznos() {
            return iznos;
        }

        /**
         * Sets the value of the iznos property.
         * 
         * @param value
         *     allowed object is
         *     {@link BigDecimal }
         *     
         */
        public void setIznos(BigDecimal value) {
            this.iznos = value;
        }

        /**
         * Gets the value of the datumValute property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
//        public XMLGregorianCalendar getDatumValute() {
//            return datumValute;
//        }
//
//        /**
//         * Sets the value of the datumValute property.
//         * 
//         * @param value
//         *     allowed object is
//         *     {@link XMLGregorianCalendar }
//         *     
//         */
//        public void setDatumValute(XMLGregorianCalendar value) {
//            this.datumValute = value;
//        }

        /**
         * Gets the value of the oznakaValute property.
         * 
         * @return
         *     possible object is
         *     {@link String }
         *     
         */
        public String getOznakaValute() {
            return oznakaValute;
        }

        /**
         * Sets the value of the oznakaValute property.
         * 
         * @param value
         *     allowed object is
         *     {@link String }
         *     
         */
        public void setOznakaValute(String value) {
            this.oznakaValute = value;
        }

		public Date getDatumValute() {
			return datumValute;
		}

		public void setDatumValute(Date datumValute) {
			this.datumValute = datumValute;
		}

		public Date getDatumNaloga() {
			return datumNaloga;
		}

		public void setDatumNaloga(Date datumNaloga) {
			this.datumNaloga = datumNaloga;
		}

        /**
         * Gets the value of the datumNaloga property.
         * 
         * @return
         *     possible object is
         *     {@link XMLGregorianCalendar }
         *     
         */
//        public XMLGregorianCalendar getDatumNaloga() {
//            return datumNaloga;
//        }
//
//        /**
//         * Sets the value of the datumNaloga property.
//         * 
//         * @param value
//         *     allowed object is
//         *     {@link XMLGregorianCalendar }
//         *     
//         */
//        public void setDatumNaloga(XMLGregorianCalendar value) {
//            this.datumNaloga = value;
//        }
        	
        
        
    }

}
