//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.7 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2017.06.19 at 02:24:19 PM CEST 
//


package korenski.soap.odobrenje;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for OdobrenjeClearing complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="OdobrenjeClearing">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="ClearingElement" type="{http://korenski/soap/odobrenje}Clearing"/>
 *         &lt;element name="PorukaElement" type="{http://korenski/soap/odobrenje}Poruka"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "OdobrenjeClearing", propOrder = {
    "clearingElement",
    "porukaElement"
})
public class OdobrenjeClearing {

    @XmlElement(name = "ClearingElement", required = true)
    protected Clearing clearingElement;
    @XmlElement(name = "PorukaElement", required = true)
    protected Poruka porukaElement;

    /**
     * Gets the value of the clearingElement property.
     * 
     * @return
     *     possible object is
     *     {@link Clearing }
     *     
     */
    public Clearing getClearingElement() {
        return clearingElement;
    }

    /**
     * Sets the value of the clearingElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Clearing }
     *     
     */
    public void setClearingElement(Clearing value) {
        this.clearingElement = value;
    }

    /**
     * Gets the value of the porukaElement property.
     * 
     * @return
     *     possible object is
     *     {@link Poruka }
     *     
     */
    public Poruka getPorukaElement() {
        return porukaElement;
    }

    /**
     * Sets the value of the porukaElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link Poruka }
     *     
     */
    public void setPorukaElement(Poruka value) {
        this.porukaElement = value;
    }

}
